### ISSUE TITLE
[2] Set up Firebase DB for Quests

### ISSUE THREAD

**Issue by Q1justin** [Quick-Silver-Stash/Tration#26]
**Details**
Set up a basic schema for quests on Firebase. Outline the different columns that the table would have and of what type each column is.

**Acceptance Criteria**
1. Create a structure DB for the Quests table

**Comment by Q1justin** [comment]
@SeungKiLeeCS  @JYC211  Here is a basic schema. As firebase is not like normal SQL where we have a set structure for a table, I will handle this ticket by writing up a design suggestion and getting it reviewed by one of you. If we are happy with it, we will write Quests with these fields into Firebase. Could you guys quickly review this for me and let me know if anything should be changed?

p.s. not sure firebase lets us define character length so I wrote numbers that I would use as character limit when a user creates a quest for those specific fields.

Quest

- **questID** (Int) => Primary Key 
- **userID** (Int) =>  Foreign Key to Users table
- **title** (Varchar 50) => name of quest that is shown 
- **description** (Varchar 255)

These two are currently set to VARCHAR but if we decide to have a lookup table, we will make them integers referencing the relevant item in the lookup table
- **questType** (Varchar 50) => e.g. excercise, nutrition, sleep
- **questFrequency** (Varchar 50) => e.g. Daily or Long Term (Could be an integer if we decide to have a lookup table)

- **isComplete** (Boolean) => If daily, we make this reset to false at midnight
- **isActive** (Boolean)
- **createdOn** (DateTime)
- **UpdatedOn** (DateTime

**Comment by seungkilee-cs** [comment]
@Q1justin 
The length does not have a limit unless we set one, and I think for description we may want larger value if we will set the char limit at all.

I think having audit fields are useful, so we should keep that as the convention in the future dev as well. In terms of the reference values, these are inherently RDBMS way of looking at things. Of course this will work and this design looks good for now but I suggest moving forward we all should familiarize ourselves with concepts like denormalized data models.

[Firebase's Structuring Data](https://firebase.google.com/docs/database/web/structure-data)
[MongoDB's References](https://docs.mongodb.com/manual/reference/database-references/)

**Comment by Q1justin** [comment]
Thank you for the review @seungkilee-cs. I have looked a bit into denormalized data models and tried to design it with what I understood. Ultimately this piece of structure will be a parameter each user has. Went over it with Seungki over a call and so far things seem good. If this seems all good Seungki, please close this ticket for me please. Of course if there is an issue, lmk

quests:{
   questid:{
      **title** (VARCHAR)
      **description** (VARCHAR)
      **questType** (VARCHAR)
      **questFrequency** (VARCHAR)
      **isComplete** (Boolean)
      **isActive** (Boolean)
      **createdOn** (dateTime)
      **updatedOn** (dateTime)
   }
}

**Comment by seungkilee-cs** [comment]
Formatting with md
```
quests:{
  questid:{
    title (VARCHAR)
    description (VARCHAR)
    questType (VARCHAR)
    questFrequency (VARCHAR)
    isComplete (Boolean)
    isActive (Boolean)
    createdOn (dateTime)
    updatedOn (dateTime)
  }
}
```
