### ISSUE TITLE
[5] Authentication Backend

### ISSUE THREAD

**Issue by seungkilee-cs** [Quick-Silver-Stash/Tration#28]
# Description

- As an user, I want to be able to create and account with my email address and password
- AS an user, I want to be able to log in with the registered credentials

# Acceptance Criteria
- [ ] 1. Can write to DB using the `Register` frontend
- [ ] 2. Can send credentials to the DB using `Login` frontend to manage session.

**Comment by Q1justin** [comment]
Moving from Sprint 3 to 4
