### ISSUE TITLE
[2] User Profile Data Structure

### ISSUE THREAD

**Issue by JYC211** [Quick-Silver-Stash/Tration#30]
I would like to be able to retrieve the following information for the User Profile:

User Profile:
•	Id
  o	First Name
  o	Middle Name
  o	Last Name
  o	Email
  o	Password (hashed?)
  o	Age
  o	Blurb
  o	Level
    	Current Exp
    	Exp To Level Up
  o	Tration
  o	Quests
    	Quest Name
    	Completed
    	Difficulty
    	Frequency
  o	Streak

**Comment by Q1justin** [comment]
Closing as this ticket is no longer needed
